# Generated by Django 4.1.7 on 2023-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
